### ISSUE TITLE
setare valori din interfata

### ISSUE THREAD

**Issue by ignatescustefan** [arrnaux/bayesian-probabilities#1]
Adaugare buton setare valori,cand dau click pe el actualizez datele din clase(Gripa,Abces,Febra,Oboseala,Anorexie) cu cele din interfata.

![image](https://user-images.githubusercontent.com/50322733/70862786-7b4dee80-1f49-11ea-852d-7f5e5b650813.png)

**Comment by arcilli** [comment]
This is no longer necessary. The values will be associated when the compute butten is pressed.
