### ISSUE TITLE
teorie

### ISSUE THREAD

**Issue by ignatescustefan** [arrnaux/bayesian-probabilities#8]
calculare functie probabilite (curs 10,pg 50)
sortare topologica (nu stiu cursul)

**Comment by ignatescustefan** [comment]
sortare topologica curs 10 ,slide 35-37

**Comment by ignatescustefan** [comment]
https://www.geeksforgeeks.org/topological-sorting-indegree-based-solution/

**Comment by arcilli** [comment]
Closed as duplicated of #4.
